
script:
  - npm test --single-run
  - node_modules/.bin/protractor test/e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "5.5.0"
before_script:
  - npm -g install npm@latest
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - sleep 3
script: make test-coveralls
sudo: false
